version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing AWS CLI if not available...
      - which aws || curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip && sudo ./aws/install
  pre_build:
    commands:
      - echo "Checking AWS CLI version..."
      - aws --version
  build:
    commands:
      - echo "Cleaning old files from S3..."
      - aws s3 rm s3://your-s3-bucket-name --recursive
      - echo "Uploading new files to S3..."
      - aws s3 cp . s3://your-s3-bucket-name --recursive --exclude "node_modules/*"

artifacts:
  files:
    - '**/*'
